on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Configure Datadog Test Visibility
        uses: nikita-tkachenko-datadog/gha-composite-test@v36
        with:
          languages: dotnet
          service-name: ci-test-project-gha
          api-key: ${{ secrets.DD_API_KEY }}
      - name: Run Tests
        run: dotnet test
        shell: bash
